# Maven
# Build your Java project and run tests with Apache Maven.
# Deploy
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
   - name: process.clean
     value: false

pool: Default

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build Maven Project
    steps:
    - task: Maven@4
      displayName: 'Compilación'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
    - task: CopyFiles@2
      displayName: 'Copiando archivos al directorio de staging'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      displayName: 'Publicación'
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: SampleSpringBootBuild
    - task: AzureRmWebAppDeployment@5
      displayName: 'Despliegue'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Suscripción 1(419482ac-f59e-4e6f-9a74-bcb5ba69c968)'
        appType: 'webAppLinux'
        WebAppName: 'RestAPIU-Q'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.jar'        
        DeploymentTypeLinux: 'oneDeploy'